# This file is expected to fail ❌ upon push until you fix the bug
# You successfully completed this level when this file pass 🟢 upon push
name: HACK - Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis-code.yml"

jobs:
  jarvis:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check for insecure actions
        run: |
          # Checking for the presence of an insecure GitHub Action
          if grep -q "uses: dduzgun-security/secure-code-game-action@" $GITHUB_WORKSPACE/.github/workflows/jarvis-code.yml; then
            echo "Insecure action detected. Please replace it with a secure one."
            exit 1
          else
            echo "No insecure actions detected."
          fi

